### ISSUE TITLE
Tests failing in node.js, also on CI

### ISSUE THREAD

**Issue by raimohanska** [yjs/yjs#745]
More than 90 tests fail with errors like

```
[87/230] array: repeat generating yarray tests43
  sync protocol doesnt support v2 protocol yet, fallback to v1 encoding
  TypeError: leftStruct.splice is not a function
```

In the output, there is this warning `Yjs was already imported. This breaks constructor checks and will lead to issues!` which might suggest that this happens because Y.js is imported twice. Which in turn might be because the tests import y-protocols that has Y.js as dependency.

I ran `git bisect` for this and it looks like the first broken commit is

```
584ad5fc9a330b659ed965b6d391234deb2240b9 is the first bad commit
commit 584ad5fc9a330b659ed965b6d391234deb2240b9 (HEAD)
Author: Kevin Jahns <kevin.jahns@protonmail.com>
Date:   Tue Oct 28 17:51:10 2025 +0100

    bump deps and use new delta format
```

More precisely it's the "bump deps" part that makes the tests fail. If I checkout the package.json and package-lock.json from the previous commit, only 10 tests fail at this commit, for different reasons (not delving into that).

If I remove package-lock.json, the tests start failing for older versions as well.

I didn't have time to dig deeper, but might do later. It would be great to have the tests fixed.

As a side-note, I might consider stripping down some of the test output as well - they are very verbose :)
